mod cpu_storage;
mod cuda_backend;
mod device;
mod dtype;
mod error;
mod shape;
mod storage;
mod tensor;
pub use device::Device;
pub use dtype::DType;
pub use error::{Error, Result};
pub use shape::{Shape, R1, R2, R3, R4, R5, R6};
pub use tensor::Tensor;
